### ISSUE TITLE
sh: 1: aws: not foundaws: not found

### ISSUE THREAD

**Issue by mehulsinhzala96** [EscVM/OIDv4_ToolKit#71]
[INFO] | Downloading Apple.

---------------------------------------------------------------------------------------------------Apple---------------------------------------------------------------------------------------------------
    [INFO] | Downloading validation images.
    [INFO] | [INFO] Found 46 online images for validation.
    [INFO] | Download of 46 images in validation.
sh: 1: sh: 1: sh: 1: aws: not foundaws: not found
aws: not found

sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:00<00:00, 326460.21it/s]
    [INFO] | Done!
    [INFO] | Creating labels for Apple of validation.
    [INFO] | Labels creation completed.
    [INFO] | Downloading Orange.

---------------------------------------------------------------------------------------------------Orange---------------------------------------------------------------------------------------------------
    [INFO] | Downloading validation images.
    [INFO] | [INFO] Found 61 online images for validation.
    [INFO] | Download of 61 images in validation.
  0%|                                                                                                                                                                                | 0/61 [00:00<?, ?it/s]sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: sh: 1: aws: not found
aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: sh: 1: aws: not found
aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: sh: 1: aws: not found
aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 61/61 [00:00<00:00, 1163.82it/s]
    [INFO] | Done!
    [INFO] | Creating labels for Orange of validation.
    [INFO] | Labels creation completed.

**Comment by Tourenathan-G5organisation** [comment]
Please help, i have this same issue on my server after installing all the requirement

**Comment by Tourenathan-G5organisation** [comment]
I finally solved the issue. This is because the **awscli** tool is not installed.
Initially i tried installing it with the command `pip3 install --user awscli` but i didn't work.
so installed it directl in the system using the command below
```
curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
```
**And it worked perfectly**

**Comment by tongxinw** [comment]
Hi, I tried 
```
curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
```
but this error shows:
```
cannot execute binary file
Found preexisting AWS CLI installation: /usr/local/aws-cli/v2/current. Please rerun install script with --update flag.
```
Anyone knows how to solve?

**Comment by heniczyna** [comment]
@tongxinw please try with already solved issue #68 

in my particular case I installed `awscli` using `conda install -c conda-forge awscli`

**Comment by Olalaye** [comment]
pip install awscli

**Comment by chrisTopp84** [comment]
Hi, my problem is very similar and i don't know how to solve it.


This error is shown (it is just a part of it):

>     [INFO] | Downloading train images.
>     [INFO] | [INFO] Found 89465 online images for train.
>     [INFO] | Limiting to 9 images.
>     [INFO] | Download of 9 images in train.
>   0%|                                                                                                                              | 0/9 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in <module>
>     import awscli.clidriver
> ModuleNotFoundError: No module named 'awscli'
> Traceback (most recent call last):
>   File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in <module>
>     import awscli.clidriver
> ModuleNotFoundError: No module named 'awscli'
> Traceback (most recent call last):
>   File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in <module>
>     import awscli.clidriver
> ModuleNotFoundError: No module named 'awscli'
> Traceback (most recent call last):
>   File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in <module>
>     import awscli.clidriver
> ModuleNotFoundError: No module named 'awscli'
> Traceback (most recent call last):
>   File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in <module>
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in <module>
>     import awscli.clidriver
> ModuleNotFoundError: No module named 'awscli'
>     import awscli.clidriver
> ModuleNotFoundError: No module named 'awscli'
>   File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in <module>
>     import awscli.clidriver
> ModuleNotFoundError: No module named 'awscli'
> Traceback (most recent call last):
>   File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in <module>
>     import awscli.clidriver
> ModuleNotFoundError: No module named 'awscli'
> Traceback (most recent call last):
>   File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in <module>
>     import awscli.clidriver
> ModuleNotFoundError: No module named 'awscli'
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 11.87it/s]
>     [INFO] | Done!
>     [INFO] | Creating labels for Car of train.
>     [INFO] | Labels creation completed.




I tried **pip3 install awcsli** to solve this problem.
Then I got this message:


> (base) C:\Users\czerny\OIDv4_Toolkit>pip3 install awscli
> Requirement already satisfied: awscli in c:\users\czerny\python\python37\lib\site-packages (1.18.104)
> Requirement already satisfied: botocore==1.17.27 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (1.17.27)
> Requirement already satisfied: docutils<0.16,>=0.10 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (0.15.2)
> Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (0.3.3)
> Requirement already satisfied: PyYAML<5.4,>=3.10 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (5.3.1)
> Requirement already satisfied: colorama<0.4.4,>=0.2.5 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (0.4.3)
> Requirement already satisfied: rsa<=4.5.0,>=3.1.2 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (4.5)
> Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\czerny\python\python37\lib\site-packages (from botocore==1.17.27->awscli) (2.8.1)
> Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\czerny\python\python37\lib\site-packages (from botocore==1.17.27->awscli) (0.10.0)
> Requirement already satisfied: urllib3<1.26,>=1.20; python_version != "3.4" in c:\users\czerny\python\python37\lib\site-packages (from botocore==1.17.27->awscli) (1.25.10)
> Requirement already satisfied: pyasn1>=0.1.3 in c:\users\czerny\python\python37\lib\site-packages (from rsa<=4.5.0,>=3.1.2->awscli) (0.4.8)
> Requirement already satisfied: six>=1.5 in c:\users\czerny\python\python37\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.17.27->awscli) (1.15.0)
> WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
> You should consider upgrading via the 'python -m pip install --upgrade pip' command.


Can sombody help me?

Thanks in advance and best regards

**Comment by rojamyuan** [comment]
I had the same problem when I was running on mac. 
I did several things to make it work finally. 
I guess what fixed it was by removing the awscli from python3 site-packages folder (which was pip installed)
and install the awscli in the system /usr/local/bin as suggested by @Tourenathan-G5organisation. or instructed on its website [here](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html).
