### ISSUE TITLE
OIDv4 download nothing only error

### ISSUE THREAD

**Issue by github2016-yuan** [EscVM/OIDv4_ToolKit#74]
I follow all the steps:
install all the 3rd library:pandas/numpy/awscli/urllib3/tqdm/opencv-python
but when I use: python main.py  downloader --classes Apple --type_csv validation

Here is what I get
 [INFO] | Downloading Apple.
Traceback (most recent call last):
  File "E:\OpenImageV4\ss\OIDv4_ToolKit\modules\downloader.py", line 25, in download
    columns, rows = os.get_terminal_size(0)
OSError: [WinError 6] ▒▒▒▒▒Ч▒▒

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 37, in <module>
    bounding_boxes_images(args, DEFAULT_OID_DIR)
  File "E:\OpenImageV4\ss\OIDv4_ToolKit\modules\bounding_boxes.py", line 70, in bounding_boxes_images
    download(args, df_val, folder[1], dataset_dir, class_name, class_code)
  File "E:\OpenImageV4\ss\OIDv4_ToolKit\modules\downloader.py", line 27, in download
    columns, rows = os.get_terminal_size(1)
OSError: [WinError 6] ▒▒▒▒▒Ч▒▒

It seems that the the error is caused by  function of  os.get_terminal_size. I try to solve it but fail.
Someone say Ubuntu system instead Windows may help. I try but still fail.

Hope some advice.

**Comment by github2016-yuan** [comment]
In ubuntu, the same operation, I get the following error:
rows, columns = os.popden('stty size','r').read().split()
AttributeError:module 'os' has no attribute '**popden**'

It seems easy to solve it but I find I can not install popden at all. 
It is a **part** of 3rd library os instead of a 3rd library.

**Comment by rajat14xy** [comment]
I am also getting this error, please any1 help

**Comment by silent-j** [comment]
This error has persisted. I am experiencing this for Windows 10
