### ISSUE TITLE
ModuleNotFoundError: No module named 'awscli' - although awscli is installed 

### ISSUE THREAD

**Issue by chrisTopp84** [EscVM/OIDv4_ToolKit#83]
Hi, my problem is very similar to issue #71  and i don't know how to solve it.

This error is shown (it is just a part of it):

    [INFO] | Downloading train images.
    [INFO] | [INFO] Found 89465 online images for train.
    [INFO] | Limiting to 9 images.
    [INFO] | Download of 9 images in train.

    0%| | 0/9 [00:00<?, ?it/s]Traceback (most recent call last):
    File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in
    import awscli.clidriver
    ModuleNotFoundError: No module named 'awscli'
    Traceback (most recent call last):
    File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in
    import awscli.clidriver
    ModuleNotFoundError: No module named 'awscli'
    Traceback (most recent call last):
    File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in
    import awscli.clidriver
    ModuleNotFoundError: No module named 'awscli'
    Traceback (most recent call last):
    File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in
    import awscli.clidriver
    ModuleNotFoundError: No module named 'awscli'
    Traceback (most recent call last):
    File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in
    Traceback (most recent call last):
    Traceback (most recent call last):
    File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in
    import awscli.clidriver
    ModuleNotFoundError: No module named 'awscli'
    import awscli.clidriver
    ModuleNotFoundError: No module named 'awscli'
    File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in
    import awscli.clidriver
    ModuleNotFoundError: No module named 'awscli'
    Traceback (most recent call last):
    File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in
    import awscli.clidriver
    ModuleNotFoundError: No module named 'awscli'
    Traceback (most recent call last):
    File "C:\Users\czerny\Python\Python37\Scripts\aws.cmd", line 50, in
    import awscli.clidriver
    ModuleNotFoundError: No module named 'awscli'
    100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 11.87it/s]
    [INFO] | Done!
    [INFO] | Creating labels for Car of train.
    [INFO] | Labels creation completed.

I tried pip3 install awcsli to solve this problem.
Then I got this message:

    (base) C:\Users\czerny\OIDv4_Toolkit>pip3 install awscli
    Requirement already satisfied: awscli in c:\users\czerny\python\python37\lib\site-packages (1.18.104)
    Requirement already satisfied: botocore==1.17.27 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (1.17.27)
    Requirement already satisfied: docutils<0.16,>=0.10 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (0.15.2)
    Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (0.3.3)
    Requirement already satisfied: PyYAML<5.4,>=3.10 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (5.3.1)
    Requirement already satisfied: colorama<0.4.4,>=0.2.5 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (0.4.3)
    Requirement already satisfied: rsa<=4.5.0,>=3.1.2 in c:\users\czerny\python\python37\lib\site-packages (from awscli) (4.5)
    Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\czerny\python\python37\lib\site-packages (from botocore==1.17.27->awscli) (2.8.1)
    Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\czerny\python\python37\lib\site-packages (from botocore==1.17.27->awscli) (0.10.0)
    Requirement already satisfied: urllib3<1.26,>=1.20; python_version != "3.4" in c:\users\czerny\python\python37\lib\site-packages (from botocore==1.17.27->awscli) (1.25.10)
    Requirement already satisfied: pyasn1>=0.1.3 in c:\users\czerny\python\python37\lib\site-packages (from rsa<=4.5.0,>=3.1.2->awscli) (0.4.8)
    Requirement already satisfied: six>=1.5 in c:\users\czerny\python\python37\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.17.27->awscli) (1.15.0)
    WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
    You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Can sombody help me?

Thanks in advance and best regards

**Comment by chrisTopp84** [comment]
I could solve the problem by creating a new environment with

`conda create -n nameofmyenvironment python=3.7.6`

in the anaconda prompt.

All the rest i could do like before.
