### ISSUE TITLE
error when running python main.py downloader

### ISSUE THREAD

**Issue by Niklaus28** [EscVM/OIDv4_ToolKit#84]
CMD : python main.py downloader --classes Football --type_csv train --limit 100

Error: Traceback (most recent call last):
  File "main.py", line 37, in <module>
    bounding_boxes_images(args, DEFAULT_OID_DIR)
  File "C:\OIDv4_ToolKit\modules\bounding_boxes.py", line 60, in bounding_boxes_images
    df_val = TTV(csv_dir, name_file, args.yes)
  File "C:\OIDv4_ToolKit\modules\csv_downloader.py", line 21, in TTV
    df_val = pd.read_csv(CSV)
  File "C:\Users\haoji\Python38\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\haoji\Python38\lib\site-packages\pandas\io\parsers.py", line 458, in _read
    data = parser.read(nrows)
  File "C:\Users\haoji\Python38\lib\site-packages\pandas\io\parsers.py", line 1186, in read
    ret = self._engine.read(nrows)
  File "C:\Users\haoji\Python38\lib\site-packages\pandas\io\parsers.py", line 2145, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 826, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 869, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 2053, in pandas._libs.parsers._concatenate_chunks
  File "<__array_function__ internals>", line 5, in concatenate
MemoryError: Unable to allocate 55.7 MiB for an array with shape (14610229,) and data type object

Please help, I followed the The AI Guy youtube video
https://www.youtube.com/watch?v=_4A9inxGqRM

**Comment by KartickVerma** [comment]
![SharedScreenshotoid](https://user-images.githubusercontent.com/48294805/89126918-5b366400-d507-11ea-8de7-791afc0b9648.jpg)

Facing the same problem, please help

**Comment by minhlenhat-itr** [comment]
have someone solved this problem yet?

**Comment by rmadduku** [comment]
I changed to python 3.7.4 64 bit, that worked for me
