### ISSUE TITLE
error while downloading images

### ISSUE THREAD

**Issue by adhilcodes** [EscVM/OIDv4_ToolKit#88]
**File "main.py", line 37, in <module>
    bounding_boxes_images(args, DEFAULT_OID_DIR)
  File "C:\Users\Abdul Adhil PK\Desktop\OIDv4_ToolKit-master\modules\bounding_boxes.py", line 56, in bounding_boxes_images
    class_code = df_classes.loc[df_classes[1] == class_name].values[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0**

**Comment by adhilcodes** [comment]
> when i typed this - **_"python main.py downloader --classes 'taxi' --type_csv train --limit 500 "_** the dataset is not started to download ,it shows the following message after typing **' Y '** ,
> 
> **Traceback (most recent call last): File "main.py", line 37, in bounding_boxes_images(args, DEFAULT_OID_DIR) File "C:\Users\Abdul Adhil PK\Desktop\OIDv4_ToolKit-master\modules\bounding_boxes.py", line 56, in bounding_boxes_images class_code = df_classes.loc[df_classes[1] == class_name].values[0][0] IndexError: index 0 is out of bounds for axis 0 with size 0**



This issue got fixed , the error was to type the class name by case sensitive.
eg:- if we want to download images of taxi we must type it as **Taxi** and not **taxi**
_**so to download image data of any classes ensure the class name is same as in the Google open image dataset website**_ .

**Comment by adhilcodes** [comment]
This issue got fixed , the error was to type the class name by case sensitive.
eg:- if we want to download images of taxi we must type it as Taxi and not taxi
so to download image data of any classes ensure the class name is same as in the Google open image dataset website .
