### ISSUE TITLE
OSError: The handle is Invalid

### ISSUE THREAD

**Issue by silent-j** [EscVM/OIDv4_ToolKit#95]
Using the Toolkit to download a single class of images on Windows 10, Python version 3.7.6

Running the downloader commands results in a WinError 6. The traceback points towards Lines 25 of the downloader file
```
Traceback (most recent call last):
  File "C:\Users\James\Documents\OIDv4_ToolKit\modules\downloader.py", line 25, in download
    columns, rows = os.get_terminal_size(0)
OSError: [WinError 6] The handle is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OIDv4_ToolKit/main.py", line 37, in <module>
    bounding_boxes_images(args, DEFAULT_OID_DIR)
  File "C:\Users\James\Documents\OIDv4_ToolKit\modules\bounding_boxes.py", line 62, in bounding_boxes_images
    download(args, df_val, folder[0], dataset_dir, class_name, class_code)
  File "C:\Users\James\Documents\OIDv4_ToolKit\modules\downloader.py", line 27, in download
    columns, rows = os.get_terminal_size(1)
OSError: [WinError 6] The handle is invalid
```

**Comment by simonm3** [comment]
i get the same error

**Comment by simonm3** [comment]
Seems to work in a powershell terminal but not a bash terminal

**Comment by dhirajkchoudhary** [comment]
I also get the same error in windows 10

**Comment by JamesMcCullochDickens** [comment]
I can confirm that this will work in a powershell terminal but not a bash terminal.

**Comment by reh1548** [comment]
I can also confirm that you need to use Powershell in order to make it work. Bash terminal like Git Bash doesn't work. Bash terminal stops working after downloading the .csv files.

**Comment by 83Rafa** [comment]
Me too. It works on Powershell
